solution/ui/.eslintrc
solution/ui/src/components/atoms/editableTotal/editableTotal.js
solution/ui/src/components/atoms/editableTotal/editableTotal.test.js
solution/ui/src/components/atoms/modal/modal.js
solution/ui/src/components/atoms/moneyInput/moneyInput.js
solution/ui/src/components/molecules/accordion/accordion.js
solution/ui/src/components/molecules/breakEvenDataTable/breakEvenDataTable.js
solution/ui/src/components/molecules/breakEvenProfileCard/breakEvenProfileCard.js
solution/ui/src/components/molecules/breakEvenResultsCard/breakEvenResultsCard.js
solution/ui/src/components/molecules/hero/hero.js
solution/ui/src/components/molecules/numbersInputForm/numbersInputForm.js
solution/ui/src/components/organisms/fixedCosts/fixedCosts.js
solution/ui/src/components/organisms/pricePerUnit/pricePerUnit.js
solution/ui/src/components/organisms/results/results.js
solution/ui/src/components/organisms/unitSales/unitSales.js
solution/ui/src/components/organisms/variableCosts/variableCosts.js

Adds prop type validation. Turns on prop validation in linter config.

TC-577 Add prop type validation

---

solution/infrastructure/config/infra/cloudformation.yml

This pull request is updating 404 errs to just go to the main page.

TC-613 - redirect 404s to index.html

---

packages/api-handler-factory/package.json
packages/serverless-backend-tools/package.json
packages/serverless-ui-tools/package.json
packages/services-container/package.json
packages/services/package.json
pnpm-lock.yaml

Upgrades all mentions of lodash in the codebase to latest version.

Update lodash to latest version

---

packages/services/package.json
pnpm-lock.yaml
solution/_templates/ui-model/new/src/models/itemsStore.yml.ejs.t
solution/_templates/ui-page/new/parts/ItemsList.js.ejs.t
solution/ui/src/components/molecules/breakEvenDataTable/breakEvenDataTable.js

This pull request removes lodash and updates code that uses it.

TC-644-replace use of lodash in bep with native dom apis

---

solution/ui/src/components/molecules/accordion/accordion.js
solution/ui/src/components/molecules/accordion/accordion.test.js

Adds react testing library tests to the accordion component

TC-670 Add RTL tests for accordion

---

solution/ui/src/components/molecules/breakEvenResultsCard/breakEvenResultsCard.test.js

Adds RTL tests for results card component

TC-672 Add tests for results card

---

solution/ui/src/components/molecules/breakEvenDataTable/breakEvenDataTable.js
solution/ui/src/components/molecules/breakEvenDataTable/breakEvenDataTable.test.js
solution/ui/src/components/molecules/header/header.test.js

Adds react testing library tests for the data table

TC-673 Add tests to break even data table

---

solution/ui/src/components/molecules/footer/footer.test.js
solution/ui/src/components/molecules/hero/hero.test.js

Adds RTL tests for footer and hero components

TC-649 Add tests for footer and hero components

---

solution/ui/src/components/molecules/numbersInputForm/numbersInputForm.test.js

Adds rtl tests to numbersInputForm component

TC-680 Add rtl tests to numbersInputForm component

---

solution/ui/src/components/organisms/variableCosts/variableCosts.js

This pull request fixes a bug for variable costs where when you click enter it should proceed to the next page.

TC-685 - add button type button for variable cost

---

solution/ui/src/components/organisms/fixedCosts/fixedCosts.js
solution/ui/src/components/organisms/pricePerUnit/pricePerUnit.js
solution/ui/src/components/organisms/pricePerUnit/pricePerUnit.test.js
solution/ui/src/components/organisms/unitSales/unitSales.js
solution/ui/src/components/organisms/variableCosts/variableCosts.js
solution/ui/src/components/organisms/variableCosts/variableCosts.test.js

Adds RTL test suite to pricePerUnit component.

TC-666 Convert pricePerUnit tests to RTL

---

solution/ui/src/components/molecules/footer/footer.less

This pull request is to change the footer spacing from 9rem to 1rem.

update footer spacing

---

solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
solution/ui/src/components/organisms/unitSales/unitSales.test.js

This pull request, writes React Testing Library tests for the break even point calculator

TC-692 - RTL tests for unitSales

---

solution/ui/src/components/organisms/results/results.test.js

This pull request writes React Testing Library for the results component

TC-691 - write rtl tests for the results component

---

solution/ui/src/semantic/site/globals/site.variables
solution/ui/src/semantic/site/modules/checkbox.overrides

TC-697 Stop checkbox label wrapping on mobile devices

---

solution/ui/src/components/molecules/accordion/accordion.less

TC-696 remove left margin from accordion content

---

solution/ui/cypress/integration/happypath.spec.js
solution/ui/src/components/organisms/variableCosts/variableCosts.js

Adds cypress tests to results page

TC-660 Add cypress tests for results page

---

pnpm-lock.yaml
solution/ui/src/components/atoms/editableTotal/editableTotal.test.js
solution/ui/src/components/organisms/fixedCosts/fixedCosts.js
solution/ui/src/components/organisms/fixedCosts/fixedCosts.test.js
solution/ui/src/components/organisms/pricePerUnit/pricePerUnit.js
solution/ui/src/components/organisms/pricePerUnit/pricePerUnit.test.js
solution/ui/src/components/organisms/results/results.test.js
solution/ui/src/components/organisms/unitSales/unitSales.test.js
solution/ui/src/components/organisms/variableCosts/variableCosts.js
solution/ui/src/components/organisms/variableCosts/variableCosts.test.js

- Scrolls price per unit into view
- Makes dark blue a class, to remove the prop validation error from semantic
- Adds scrollIntoView mock to test files

TC-698 mobile focus

---

pnpm-lock.yaml
solution/ui/package.json

This pull request is upgrading gatsby to the latest version

update gatsby to latest version to see if it fixes some of the security vulnerabilities

---

README.md
solution/infrastructure/config/infra/cloudformation.yml
solution/infrastructure/config/settings/.defaults.yml

Addressing the trailing slash problem.

function changes

---

.circleci/config.yml

Changed config to install a specific version of serverless to fix build errors.

Changed version on serverless to v1

---

solution/ui/src/pages/index.js

This pull request, corrects the doman address which is https not http so it can find when the app is on mint.

Update the domain address

---

.gitignore
solution/ui/gatsby-config.js
solution/ui/src/pages/index.js

this pull requests sets up the application to use process.env to determine what environment the app is on.

try to run this with process.env instead

---

solution/ui/gatsby-ssr.js
solution/ui/src/pages/index.js

This pull request points feedback form to the prod cdn and updates the tag.

point feedbackform to prod and update index.js feedback-form tag

---

solution/ui/cypress/integration/happypath.spec.js
solution/ui/src/components/organisms/results/results.js

https://us-sba.atlassian.net/secure/RapidBoard.jspa?rapidView=51&projectKey=TC&modal=detail&selectedIssue=TC-1040
Feedback button shows up on the main page but when you run the calculator and view the results the feedback button disappears. Thats because its a different js file rendering results so feedback-form component needed to be added there.

TC-1040 fix feedback button disappearing on BEPC results
